### PR TITLE
Install CI and some linters

### PR DESCRIPTION
**Pull request by RealOrangeOne**
Install some liters to enforce code formatting, and add CI to ensure it stays that way.

### CODE REVIEW

**Comment by hrehfeld** [comment]
Awesome, thanks for providing this! I merged it manually via 69adfa3d6f5aaf4516af30c8faf6794e80d29d5c and before to be able to check the changes (I didn't commit the ' -> " conversion)

**Comment by RealOrangeOne** [comment]
@hrehfeld Seems you've completely rewritten the commits, removing even my name from them. Was that intentional? Was there a reason not to just hit merge on the PR?

**Comment by hrehfeld** [comment]
@RealOrangeOne yeah, sorry about that -- your commits weren't atomic enough to merge directly (and dropping some), so I went through everything manually. Could've edited your commits, but that's even worse IMHO. Retaining string quotes and dict() constructor calls were important to me, and also to see exactly what changes were caused by which tool.

**Comment by RealOrangeOne** [comment]
I could have squashed the commits if that was an issue. Yeah I totally get wanting to look through the changes weird tools are doing for yourself, and i'd be happy to have made changes if you'd asked.

**Pull request closed without merging**
